version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: carteirinha
    command: npm run start
    ports:
        - 3000:3000
    environment:
      - DB_URI=mongodb://mongodb:27017/carteirinha
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null